package audioeffect

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

/*
Cuts frequencies higher than the [member cutoff_hz] and allows lower frequencies to pass.
*/
type AudioEffectLowPassFilter struct {
	AudioEffectFilter
}

func (o *AudioEffectLowPassFilter) BaseClass() string {
	return "AudioEffectLowPassFilter"
}

/*
   AudioEffectLowPassFilterImplementer is an interface for AudioEffectLowPassFilter objects.
*/
type AudioEffectLowPassFilterImplementer interface {
	Class
}
