package cubemesh

import (
	"log"
	"reflect"

	"github.com/shadowapex/godot-go/gdnative"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

/*
Generate an axis-aligned cuboid [PrimitiveMesh].
*/
type CubeMesh struct {
	PrimitiveMesh
}

func (o *CubeMesh) BaseClass() string {
	return "CubeMesh"
}

/*
   Undocumented
*/
func (o *CubeMesh) GetSize() *Vector3 {
	log.Println("Calling CubeMesh.GetSize()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := o.callParentMethod(o.BaseClass(), "get_size", goArguments, "*Vector3")

	returnValue := goRet.Interface().(*Vector3)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Undocumented
*/
func (o *CubeMesh) GetSubdivideDepth() gdnative.Int {
	log.Println("Calling CubeMesh.GetSubdivideDepth()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := o.callParentMethod(o.BaseClass(), "get_subdivide_depth", goArguments, "gdnative.Int")

	returnValue := goRet.Interface().(gdnative.Int)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Undocumented
*/
func (o *CubeMesh) GetSubdivideHeight() gdnative.Int {
	log.Println("Calling CubeMesh.GetSubdivideHeight()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := o.callParentMethod(o.BaseClass(), "get_subdivide_height", goArguments, "gdnative.Int")

	returnValue := goRet.Interface().(gdnative.Int)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Undocumented
*/
func (o *CubeMesh) GetSubdivideWidth() gdnative.Int {
	log.Println("Calling CubeMesh.GetSubdivideWidth()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := o.callParentMethod(o.BaseClass(), "get_subdivide_width", goArguments, "gdnative.Int")

	returnValue := goRet.Interface().(gdnative.Int)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Undocumented
*/
func (o *CubeMesh) SetSize(size *Vector3) {
	log.Println("Calling CubeMesh.SetSize()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(size)

	// Call the parent method.

	o.callParentMethod(o.BaseClass(), "set_size", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Undocumented
*/
func (o *CubeMesh) SetSubdivideDepth(divisions gdnative.Int) {
	log.Println("Calling CubeMesh.SetSubdivideDepth()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(divisions)

	// Call the parent method.

	o.callParentMethod(o.BaseClass(), "set_subdivide_depth", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Undocumented
*/
func (o *CubeMesh) SetSubdivideHeight(divisions gdnative.Int) {
	log.Println("Calling CubeMesh.SetSubdivideHeight()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(divisions)

	// Call the parent method.

	o.callParentMethod(o.BaseClass(), "set_subdivide_height", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Undocumented
*/
func (o *CubeMesh) SetSubdivideWidth(subdivide gdnative.Int) {
	log.Println("Calling CubeMesh.SetSubdivideWidth()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(subdivide)

	// Call the parent method.

	o.callParentMethod(o.BaseClass(), "set_subdivide_width", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   CubeMeshImplementer is an interface for CubeMesh objects.
*/
type CubeMeshImplementer interface {
	Class
}
