package visualscript

import (
	"github.com/shadowapex/godot-go/gdnative"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

func NewVisualScriptConditionFromPointer(ptr gdnative.Pointer) *VisualScriptCondition {
	owner := gdnative.NewObjectFromPointer(ptr)
	obj := VisualScriptCondition{}
	obj.SetOwner(owner)

	return &obj

}

/*
Undocumented
*/
type VisualScriptCondition struct {
	VisualScriptNode
}

func (o *VisualScriptCondition) BaseClass() string {
	return "VisualScriptCondition"
}
