package visualscript

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

/*
Undocumented
*/
type VisualScriptWhile struct {
	VisualScriptNode
}

func (o *VisualScriptWhile) BaseClass() string {
	return "VisualScriptWhile"
}

/*
   VisualScriptWhileImplementer is an interface for VisualScriptWhile objects.
*/
type VisualScriptWhileImplementer interface {
	Class
}
