package visualscript

import (
	"log"
	"reflect"

	"github.com/shadowapex/godot-go/gdnative"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

/*
Undocumented
*/
type VisualScriptReturn struct {
	VisualScriptNode
}

func (o *VisualScriptReturn) BaseClass() string {
	return "VisualScriptReturn"
}

/*
   Undocumented
*/
func (o *VisualScriptReturn) GetReturnType() gdnative.Int {
	log.Println("Calling VisualScriptReturn.GetReturnType()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := o.callParentMethod(o.BaseClass(), "get_return_type", goArguments, "gdnative.Int")

	returnValue := goRet.Interface().(gdnative.Int)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Undocumented
*/
func (o *VisualScriptReturn) IsReturnValueEnabled() gdnative.Bool {
	log.Println("Calling VisualScriptReturn.IsReturnValueEnabled()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := o.callParentMethod(o.BaseClass(), "is_return_value_enabled", goArguments, "gdnative.Bool")

	returnValue := goRet.Interface().(gdnative.Bool)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Undocumented
*/
func (o *VisualScriptReturn) SetEnableReturnValue(enable gdnative.Bool) {
	log.Println("Calling VisualScriptReturn.SetEnableReturnValue()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(enable)

	// Call the parent method.

	o.callParentMethod(o.BaseClass(), "set_enable_return_value", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   Undocumented
*/
func (o *VisualScriptReturn) SetReturnType(aType gdnative.Int) {
	log.Println("Calling VisualScriptReturn.SetReturnType()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(aType)

	// Call the parent method.

	o.callParentMethod(o.BaseClass(), "set_return_type", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   VisualScriptReturnImplementer is an interface for VisualScriptReturn objects.
*/
type VisualScriptReturnImplementer interface {
	Class
}
