package visualscript

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

/*
Undocumented
*/
type VisualScriptIndexGet struct {
	VisualScriptNode
}

func (o *VisualScriptIndexGet) BaseClass() string {
	return "VisualScriptIndexGet"
}

/*
   VisualScriptIndexGetImplementer is an interface for VisualScriptIndexGet objects.
*/
type VisualScriptIndexGetImplementer interface {
	Class
}
