package visualscript

import (
	"log"

	"github.com/shadowapex/godot-go/gdnative"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

func NewVisualScriptSubCallFromPointer(ptr gdnative.Pointer) *VisualScriptSubCall {
	owner := gdnative.NewObjectFromPointer(ptr)
	obj := VisualScriptSubCall{}
	obj.SetOwner(owner)

	return &obj

}

/*
Undocumented
*/
type VisualScriptSubCall struct {
	VisualScriptNode
}

func (o *VisualScriptSubCall) BaseClass() string {
	return "VisualScriptSubCall"
}

/*
        Undocumented
	Args: [{ false arguments Variant}], Returns: Variant
*/

func (o *VisualScriptSubCall) X_Subcall(arguments gdnative.Variant) gdnative.Variant {
	log.Println("Calling VisualScriptSubCall.X_Subcall()")

	// Build out the method's arguments
	ptrArguments := make([]gdnative.Pointer, 1, 1)
	ptrArguments[0] = gdnative.NewPointerFromVariant(arguments)

	// Get the method bind
	methodBind := gdnative.NewMethodBind("VisualScriptSubCall", "_subcall")

	// Call the parent method.
	// Variant
	retPtr := gdnative.NewEmptyVariant()
	gdnative.MethodBindPtrCall(methodBind, o.GetOwner(), ptrArguments, retPtr)

	// If we have a return type, convert it from a pointer into its actual object.
	ret := gdnative.NewVariantFromPointer(retPtr)

	log.Println("  Got return value: ", ret)
	return ret
}
