package class

import (
	"github.com/shadowapex/godot-go/gdnative"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

//func NewResourceImporterTheoraFromPointer(ptr gdnative.Pointer) ResourceImporterTheora {
func NewResourceImporterTheoraFromPointer(ptr gdnative.Pointer) ResourceImporterTheora {
	owner := gdnative.NewObjectFromPointer(ptr)
	obj := ResourceImporterTheora{}
	obj.SetBaseObject(owner)

	return obj
}

/*
Undocumented
*/
type ResourceImporterTheora struct {
	ResourceImporter
	owner gdnative.Object
}

func (o *ResourceImporterTheora) BaseClass() string {
	return "ResourceImporterTheora"
}
