package encodedobjectasid

import (
	"log"
	"reflect"

	"github.com/shadowapex/godot-go/gdnative"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

/*

 */
type EncodedObjectAsID struct {
	Reference
}

func (o *EncodedObjectAsID) BaseClass() string {
	return "EncodedObjectAsID"
}

/*

 */
func (o *EncodedObjectAsID) GetObjectId() gdnative.Int {
	log.Println("Calling EncodedObjectAsID.GetObjectId()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := o.callParentMethod(o.BaseClass(), "get_object_id", goArguments, "gdnative.Int")

	returnValue := goRet.Interface().(gdnative.Int)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*

 */
func (o *EncodedObjectAsID) SetObjectId(id gdnative.Int) {
	log.Println("Calling EncodedObjectAsID.SetObjectId()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(id)

	// Call the parent method.

	o.callParentMethod(o.BaseClass(), "set_object_id", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   EncodedObjectAsIDImplementer is an interface for EncodedObjectAsID objects.
*/
type EncodedObjectAsIDImplementer interface {
	Class
}
