package canvasmodulate

import (
	"log"
	"reflect"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

/*
[code]CanvasModulate[/code] tints the canvas elements using its assigned [code]color[/code].
*/
type CanvasModulate struct {
	Node2D
}

func (o *CanvasModulate) BaseClass() string {
	return "CanvasModulate"
}

/*
   Undocumented
*/
func (o *CanvasModulate) GetColor() *Color {
	log.Println("Calling CanvasModulate.GetColor()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 0, 0)

	// Call the parent method.

	goRet := o.callParentMethod(o.BaseClass(), "get_color", goArguments, "*Color")

	returnValue := goRet.Interface().(*Color)

	log.Println("  Got return value: ", returnValue)
	return returnValue

}

/*
   Undocumented
*/
func (o *CanvasModulate) SetColor(color *Color) {
	log.Println("Calling CanvasModulate.SetColor()")

	// Build out the method's arguments
	goArguments := make([]reflect.Value, 1, 1)
	goArguments[0] = reflect.ValueOf(color)

	// Call the parent method.

	o.callParentMethod(o.BaseClass(), "set_color", goArguments, "")

	log.Println("  Function successfully completed.")

}

/*
   CanvasModulateImplementer is an interface for CanvasModulate objects.
*/
type CanvasModulateImplementer interface {
	Class
}
