package checkbox

import (
	"github.com/shadowapex/godot-go/gdnative"
	"github.com/shadowapex/godot-go/godot/class/button"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

func NewCheckBoxFromPointer(ptr gdnative.Pointer) *CheckBox {
	owner := gdnative.NewObjectFromPointer(ptr)
	obj := CheckBox{}
	obj.SetOwner(owner)

	return &obj

}

/*
A checkbox allows the user to make a binary choice (choosing only one of two possible options), for example Answer 'yes' or 'no'.
*/
type CheckBox struct {
	button.Button
}

func (o *CheckBox) BaseClass() string {
	return "CheckBox"
}
