package vscrollbar

import (
	"github.com/shadowapex/godot-go/gdnative"
	"github.com/shadowapex/godot-go/godot/class/scrollbar"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

func NewVScrollBarFromPointer(ptr gdnative.Pointer) *VScrollBar {
	owner := gdnative.NewObjectFromPointer(ptr)
	obj := VScrollBar{}
	obj.SetOwner(owner)

	return &obj

}

/*

 */
type VScrollBar struct {
	scrollbar.ScrollBar
}

func (o *VScrollBar) BaseClass() string {
	return "VScrollBar"
}
